on:
  push:
    branches:
      - demo-recording
jobs:
  franklin-bridge:
    if: "contains(github.event.head_commit.message, 'Bridge')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - run: npm install
      - run: node htmlParser.js
