on:
  push:
    branches:
      - demo-recording
jobs:
  franklin-bridge:
    if: "contains(github.event.head_commit.message, 'Bridge')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - run: npm install
      # - run: node htmlParser.js
      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: main content json
      #     path: websitedata.json
      - run: node websiteDataDownloader.js
      - uses: actions/upload-artifact@v3
        with:
          name: entire-website-data
          path: data/
      - run: node htmlToJson.js
      - uses: actions/upload-artifact@v3
        with:
          name: Parsed data json
          path: artifact/parsed_data.json
      # - uses: shallwefootball/s3-upload-action@master
      #   id: S3
      #   with:
      #     aws_key_id: ${{secrets.AWS_KEY_ID}}
      #     aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      #     aws_bucket: pwa-setup
      #     source_dir: artifact
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy to S3
        run: aws s3 sync artifact s3://pwa-setup
